<a href="https://colab.research.google.com/github/sololzano/ICDF-Python2021/blob/main/W2_Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Iterable Objects

## Lists

<ul>
 <li>Collection of items of different types.
 <li>Items can be changed, removed, etc...
 <li>Allows duplicates.
 <li>Enclosed by square brackes, items separated by comma (<code>[1, 'a', 3]</code>).
</ul>

In [1]:
# List with different items and types
x = [1, 3.0, 'ab', False]
print(x)

[1, 3.0, 'ab', False]


In [2]:
# Change item of list by indexing
x[1] = 3.5
print(x)

[1, 3.5, 'ab', False]


## Tuples

<ul>
 <li>Collection of items of different types.
 <li>Items cannot be changed or deleted.
 <li>Allows duplicates.
 <li>Enclosed by parentheses, items separated by comma (<code>(1, 'a', 3)</code>).
</ul>

In [3]:
# Tuple with different items and types
y = (1, 3.0, 'ab', True)
print(y)

(1, 3.0, 'ab', True)


In [4]:
# Tuple items cannot be changed!
y[0] = 1.3
print(y)

TypeError: ignored

## Dictionaries

<ul>
 <li>Collection of items as <code>key:value</code>.
 <li>Items can be changed, removed, etc...
 <li>No duplicates for <code>key</code>.
 <li>Enclosed by braces, pairs separated by comma (<code>{'key1':val1, 'key2':val2, 'key3':val3}</code>).
 <li>Keys are <code>string</code>.
</ul>

In [5]:
# Create a dictionary with different items and types
d = {'key1':1, 'key2':3.2, 'key3':'ab', 'key4':False}
print(d)

{'key1': 1, 'key2': 3.2, 'key3': 'ab', 'key4': False}


In [6]:
# Access items of dictionary by key
print(d['key3'])

ab


In [7]:
# Change item value of dictionary
d['key2'] = 5.5
print(d)

{'key1': 1, 'key2': 5.5, 'key3': 'ab', 'key4': False}


## Built-in functions for Iterables


<ul>
  <li><code>sum()</code>: Sums elements of iterable. All elements must be numbers!
</ul>

In [8]:
l1 = [10, 20, 1, 3.1]
print(sum(l1))

34.1


<ul>
  <li><code>max()</code>: Returns the maximum value item (works with strings too). 
  <li><code>min()</code>: Returns the minimum value item (works with strings too).
</ul>

In [9]:
l2 = [11, 10, 3, 4, 6, -2]
print('Minimum', min(l2), '/ Maximum', max(l2))

Minimum -2 / Maximum 11


<ul>
  <li><code>sorted()</code>: Returns the sorted iterable (can be ascending or descending order with the <code>reverse</code> optional argument).
</ul>

In [10]:
# Ascending order
print(l2)
print(sorted(l2))

[11, 10, 3, 4, 6, -2]
[-2, 3, 4, 6, 10, 11]


In [11]:
# Descending order
print(l2)
print(sorted(l2, reverse=True))

[11, 10, 3, 4, 6, -2]
[11, 10, 6, 4, 3, -2]


# NumPy - Numerial Python

##N-dimensional Arrays

<ul>
  <li>Collection of items of the same type (attribute <code>dtype</code>).
  <li>Usually with fixed size (<code>shape</code>).
  <li>Broadcasting rules for linear algebra.
</ul>

In [12]:
# Import NumPy library
import numpy as np

In [13]:
# Create an array from a list
l3 = [1, 2, 3, 6, -3]
n1 = np.array(l3)
print(n1)
print(n1.shape)
print(n1.dtype)

[ 1  2  3  6 -3]
(5,)
int64


In [16]:
# 2-D array
n2 = np.array([[1, 2, 3], [4, 5, 6]])
print(n2)
print()
print(n2.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [17]:
# Type conversion
print(n2.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]]


In [19]:
# From float to int
n3 = np.array([[1, 4], [2, 5], [3, 6]], dtype=float)
print(n3)
print()
print(n3.shape)

[[1. 4.]
 [2. 5.]
 [3. 6.]]

(3, 2)


In [20]:
# Generate random arrays
n4 = np.random.uniform(-1, 1, (2, 5))
print(n4)

[[-0.57074184  0.58626744 -0.39809291 -0.65823717 -0.31402579]
 [ 0.26720055 -0.00956142 -0.20215765 -0.69062513 -0.99602344]]


In [21]:
# Reshape array
n5 = np.random.randint(0, 10, (3, 4))
print(n5)
n6 = np.reshape(n5, (6, 2))
print(n6)

[[3 5 2 5]
 [2 3 0 2]
 [1 9 5 5]]
[[3 5]
 [2 5]
 [2 3]
 [0 2]
 [1 9]
 [5 5]]


# Conditional Blocks

<ul>
  <li>Equality (<code>a == b</code>).
  <li>Inequality (<code>a != b</code>).
  <li>Less or equal than (<code>a <= b</code>).
  <li>Greater or equal than (<code>a >= b</code>).
</ul>
<i>The blocks are separated by indentation levels!!!</i>

In [27]:
s = 'ABC'
if s == 'ABC':
  print('Variable "s" equals to "ABC"')

Variable "s" equals to "ABC"


In [28]:
if s == 'abc':
  print('Variable "s" equals to "abc"')
else:
  print('Variable "s" does not equals to "abc"')

Variable "s" does not equals to "abc"


In [29]:
# Conditionals using lists
l2 = ['Apple', 'Banana', 'Pear', 'Orange']
if 'apple' in l2:
  print('"apple" in list...')
elif 'APPLE' in l2:
  print('"APPLE" in list...')
elif 'Apple' in l2:
  print('"Apple" in list...')

"Apple" in list...


In [34]:
# Comparing 2 lists
l3 = ['Apple', 'Pear', 'Orange', 'Banana']
if (l3 == l2):
  print('Lists are equal')
else:
  print('Lists are not equal')

Lists are not equal


#Loops

## While Loop

As long as a condition is met, the block is executed repeatedly.

In [35]:
# Set a counter and finish the loop until 10
c = 0
while (c < 10):
  print('Counter value', c)
  c += 1

Counter value 0
Counter value 1
Counter value 2
Counter value 3
Counter value 4
Counter value 5
Counter value 6
Counter value 7
Counter value 8
Counter value 9


In [36]:
# If the condition is not met, the loop won't be executed
c = 10
while (c < 10):
  print('Counter value', c)
  c += 1

## For Loop

Iterates through a sequence (iterable), item by item.

In [39]:
# Iterate trhough a list
l4 = ['Apple', 5, 'a', 3.4, False]
for item in l4:
  print(item)

Apple
5
a
3.4
False


In [40]:
# Enumeration is used to keep a counter for the items
for i, item in enumerate(l4):
  print('Number', i, '/ Item', item)

Number 0 / Item Apple
Number 1 / Item 5
Number 2 / Item a
Number 3 / Item 3.4
Number 4 / Item False


In [41]:
# Zip for parallel access to iterables
l5 = ['Banana', 4, 'b', 2.1, True]
for item1, item2 in zip(l4, l5):
  print('Item 1', item1, '/ Item 2', item2)

Item 1 Apple / Item 2 Banana
Item 1 5 / Item 2 4
Item 1 a / Item 2 b
Item 1 3.4 / Item 2 2.1
Item 1 False / Item 2 True


In [43]:
# Access the iterable in reverse
print(l4)
for item in reversed(l4):
  print(item)

['Apple', 5, 'a', 3.4, False]
False
3.4
a
5
Apple
